// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    CliCommandLine: typeof import('./src/components/CliCommandLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WhoAmI: typeof import('./src/components/WhoAmI.vue')['default']
    WhoIs: typeof import('./src/components/WhoIs.vue')['default']
  }
}

export {}
